/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as accessControlHelpers from "../accessControlHelpers.js";
import type * as accessTokenHelper from "../accessTokenHelper.js";
import type * as accessTokenHelperAction from "../accessTokenHelperAction.js";
import type * as activities_activities from "../activities/activities.js";
import type * as activities_activityHelpers from "../activities/activityHelpers.js";
import type * as brandTemplateSettings from "../brandTemplateSettings.js";
import type * as campaigns_autofillJobs from "../campaigns/autofillJobs.js";
import type * as campaigns_campaignActions from "../campaigns/campaignActions.js";
import type * as campaigns_campaignFunctions from "../campaigns/campaignFunctions.js";
import type * as campaigns_designs from "../campaigns/designs.js";
import type * as canvaApi from "../canvaApi.js";
import type * as canvaAuth from "../canvaAuth.js";
import type * as crons from "../crons.js";
import type * as customers from "../customers.js";
import type * as invitations from "../invitations.js";
import type * as metrics from "../metrics.js";
import type * as organizations from "../organizations.js";
import type * as userManagement from "../userManagement.js";
import type * as utils from "../utils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  accessControlHelpers: typeof accessControlHelpers;
  accessTokenHelper: typeof accessTokenHelper;
  accessTokenHelperAction: typeof accessTokenHelperAction;
  "activities/activities": typeof activities_activities;
  "activities/activityHelpers": typeof activities_activityHelpers;
  brandTemplateSettings: typeof brandTemplateSettings;
  "campaigns/autofillJobs": typeof campaigns_autofillJobs;
  "campaigns/campaignActions": typeof campaigns_campaignActions;
  "campaigns/campaignFunctions": typeof campaigns_campaignFunctions;
  "campaigns/designs": typeof campaigns_designs;
  canvaApi: typeof canvaApi;
  canvaAuth: typeof canvaAuth;
  crons: typeof crons;
  customers: typeof customers;
  invitations: typeof invitations;
  metrics: typeof metrics;
  organizations: typeof organizations;
  userManagement: typeof userManagement;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
